account/urls.py
from django.urls import path, include

from . import views
# from django.contrib.auth.views import (
#     LoginView, 
#     LogoutView, 
#     PasswordChangeView,
#     PasswordChangeDoneView,
#     PasswordResetView,
#     PasswordResetDoneView,
#     PasswordResetConfirmView,
#     PasswordResetCompleteView,
# )

app_name = 'account'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('accounts/', views.include('django.contrib.auth.urls')),
    path('account/register/', views.register, name='register'),
    path('account/edit/', views.edit, name='edit'),
    path('account/users/', views.user_list, name='user_list'),
    path('account/users/follow/', views.user_follow, name='user_follow'),
    path('account/users/<slug:slug>-<uuid:uuid>/', views.user_detail, name='user_detail'),
]

# path('login/', LoginView.as_view(), name='login'),
# path('logout/', LogoutView.as_view(), name='logout'),
# path('password-change/', PasswordChangeView.as_view(),
#     name='password_change'),
# path('password-change/done/', PasswordChangeDoneView.as_view(),
#     name='password_change_done'),
# path('password-reset/', PasswordResetView.as_view(),
#     name='password_reset'),
# path('password-reset/done/', PasswordResetDoneView.as_view(),
#     name='password_reset_done'),
# path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
#     name='password_reset_confirm'),
# path('password-reset/complete/', PasswordResetCompleteView.as_view(),
#     name='password_reset_complete'),

bookmark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from .views import *


app_name='images'

urlpatterns = [
    path('', image_list, name='list'),
    path('create/', image_create, name='create'),
    path('update/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         image_update, name='image_update'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         image_detail, name='image_detail'),
    path('like/', image_like, name='like'),
    path('ranking/', image_ranking, name='ranking'),
]

images/models.py
import os, datetime
from django.db import models
from django.conf import settings
from django.utils.text import slugify


def user_directory_path(instance, filename):
    return os.path.join(
        'bookmarked_images',
        instance.user.username,
        datetime.datetime.now().strftime('%Y/%m/%d'), 
        filename)
    
    
class Image(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='images',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, unique_for_date='created')
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to=user_directory_path)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_images', blank=True)
    total_likes = models.PositiveIntegerField(default=0)
    
    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes']),
        ]
        ordering = ['-created']
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title

images/forms.py
import requests
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms

from .models import Image

        
class ImageCreateForm(forms.ModelForm):
    class Meta:
        model  = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput,
        }
    
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if title:
            if Image.objects.filter(title=title).exists():
                raise forms.ValidationError(
                    'This title already exists. Please choose a different title.'
                )
        return title
    
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png', 'webp', 'gif']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError(
                'The given URL does not match valid image extensions.'
            )
        return url
    
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given URL
        response = requests.get(image_url)
        image.image.save(
            image_name,
            ContentFile(response.content),
            save=False
        )
        if commit:
            image.save()
        return image


class ImageUpdateForm(forms.ModelForm):
    class Meta:
        model  = Image
        fields = ['title', 'url', 'image', 'description']

images/views.py
import redis
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden

from .forms import ImageCreateForm, ImageUpdateForm
from .models import Image

from actions.utils import create_action


# Connect to redis
r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'create_image.html', {'section': 'images', 'form': form})


@login_required
def image_update(request, year, month, day, slug):
    image = get_object_or_404(
        Image, created__year=year, created__month=month, created__day=day, slug=slug)

    if image.user != request.user:
        return HttpResponseForbidden("You are not allowed to edit this image.")

    if request.method == 'POST':
        form = ImageUpdateForm(
            instance=image, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Image updated successfully.')
            return redirect(image.get_absolute_url())
    else:
        form = ImageUpdateForm(instance=image)

    return render(request, 'create_image.html', {'section': 'images', 'form': form, 'is_update': True})


@login_required
def image_detail(request, year, month, day, slug):
    image = get_object_or_404(
        Image, created__year=year, created__month=month, created__day=day, slug=slug)
    
    # Increment total image views by 1
    total_views = r.incr(f'image:{year}:{month}:{day}:{slug}:views')

    # Increment image ranking by 1
    r.zincrby('image_ranking', 1, image.id)

    follower_ids = image.user.followers.values_list('id', flat=True)
    if request.user.id in follower_ids or request.user == image.user:
        return render(request, 'image_detail.html', 
            {'section': 'images', 'image': image, 'total_views': total_views})
    else:
        return JsonResponse({'status': 'error', 'message': 'You are not authorized to access this page.'})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.liked_by.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.liked_by.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Invalid Image URL or Image does not exist.'})
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    following_ids = request.user.following.values_list('id', flat=True)
    images = Image.objects.filter(user_id__in=following_ids)
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # If AJAX request and page out of range, return an empty page
            return HttpResponse('')
        # If page out of range return last page of results
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(
            request, 'list_images.html', {'section': 'images', 'images': images})
        
    return render(request,'list.html',{'section': 'images', 'images': images})


@login_required
def image_ranking(request):
    # Get image ranking dictionary
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # Get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, 'images_ranking.html', {'section': 'images', 'most_viewed': most_viewed})

images/templates/create_image.html
{% extends "base.html" %}
{% block title %}
    {% if is_update %}
        Edit Image
    {% else %}
        Bookmark an Image
    {% endif %}
{% endblock %}
{% block content %}
     <h1>
        {% if is_update %}
            Edit Your Image
        {% else %}
            Bookmark an Image
        {% endif %}
    </h1>
    {% if request.GET.url %}
        <img src="{{ request.GET.url }}" class="image-preview">
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if is_update %}
            <input type="submit" value="Edit Image">
        {% else %}
            <input type="submit" value="Bookmark it!">
        {% endif %}
        
    </form>
{% endblock %}

images/templates/image_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    {% if request.user in image.user.followers.all or request.user == image.user %}
    <h1>
        {{ image.title }}
        {% if request.user == image.user %}
            <a href="
                {% url 'images:image_update' image.created.year image.created.month image.created.day image.slug %}" class="button">
                Edit
            </a>
        {% endif %}
    </h1>
        <a href="{{ image.image.url }}">
            <img src="{% thumbnail image.image 300x0 quality=100 %}" 
                class="image-detail" title="{{ image.title }}" alt="{{ image.title }}">
        </a>
        {% with total_likes=image.liked_by.count image_likes=image.liked_by.all %}
            <div class="image-info">
                <div>
                    <span class="count">
                        <span class="total">{{ total_likes }}</span>
                        like{{ total_likes|pluralize }}
                    </span>
                     <span class="count">
                        {{ total_views }} view{{ total_views|pluralize }}
                    </span>
                    <a href="#" data-id="{{ image.id }}" 
                        data-action="{% if request.user in image_likes %}un{% endif %}like"
                        class="like button">
                        {% if request.user not in image_likes %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </a>
                </div>
                {{ image.description|linebreaks }}
                <p>
                    By <a href="{{image.user.get_absolute_url}}">
                        {{ image.user.get_fullname|default:image.user.username }}
                    </a>
                </p>
            </div>
            <div class="image-likes">
                {% for user in image.liked_by.all %}
                    <div>
                        {% if user.photo %}
                            <img src="{{ user.photo.url }}" class="avatar" 
                                alt="{{ user.username }}'s profile picture" title="{{ user.username }}'s profile picture">
                        {% endif %}
                        <p><a href="{% url 'account:user_detail' user.slug user.uuid %}">{{ user.first_name }}</a></p>
                    </div>
                {% empty %}
                    Nobody likes this image yet.
                {% endfor %}
            </div>
        {% endwith %}
    {% else %}
        <p>You don't have permsion to see this Image</p>
    {% endif %}
{% endblock %}
{% block domready %}
    const url = '{% url "images:like" %}';
    var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
    }
    document.querySelector('a.like').addEventListener('click', function(e){
        e.preventDefault();
        var likeButton = this;
        // add request body
        var formData = new FormData();
        formData.append('id', likeButton.dataset.id);
        formData.append('action', likeButton.dataset.action);
        options['body'] = formData;
        // send HTTP request
        fetch(url, options)
        .then(response => response.json())
        .then(data => {
            if (data['status'] === 'ok')
            {
                var previousAction = likeButton.dataset.action;
                // toggle button text and data-action
                var action = previousAction === 'like' ? 'unlike' : 'like';
                likeButton.dataset.action = action;
                likeButton.innerHTML = action;
                // update like count
                var likeCount = document.querySelector('span.count .total');
                var totalLikes = parseInt(likeCount.innerHTML);
                likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
            }
        })
    });
 {% endblock %}

images/templates/images_ranking.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
    <h1>Images ranking</h1>
    <ol>
        {% for image in most_viewed %}
            <li>
                <a href="{{ image.get_absolute_url }}">
                    {{ image.title }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

images/templates/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h1>Your Feed</h1>
    <div id="image-list">
        {% include "list_images.html" %}
    </div>
{% endblock %}
{% block domready %}
    var page = 1;
    var emptyPage = false;
    var blockRequest = false;
    window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
        blockRequest = true;
        page += 1;
        fetch('?images_only=1&page=' + page)
        .then(response => response.text())
        .then(html => {
        if (html === '') {
            emptyPage = true;
        }
        else {
            var imageList = document.getElementById('image-list');
            imageList.insertAdjacentHTML('beforeEnd', html);
            blockRequest = false;
        }
        })
    }
    });
    // Launch scroll event
    const scrollEvent = new Event('scroll');
    window.dispatchEvent(scrollEvent);
{% endblock %}

images/templates/list_images.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}" title="{{ image.title }}" alt="{{ image.title }}">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}